{{- if .Values.migrateJob.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-sites-{{ template "erpnext.fullname" . }}-{{ date "20060102150405" .Release.Now }}
spec:
  backoffLimit: 1
  template:
    spec:
      securityContext:
        supplementalGroups: [1000]
      initContainers:
      - name: set-maintenance-mode
        image: stedolan/jq
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args:
          - cp /data/common_site_config.json /data/temp.json;
            jq -r '.maintenance_mode=1 | .pause_scheduler=1' /data/temp.json > /data/common_site_config.json;
            chown 1000:1000 /data/common_site_config.json;
            rm /data/temp.json;
        volumeMounts:
          - name: sites-dir
            mountPath: "/data"
      {{- if .Values.migrateJob.backup }}
      - name: backup
        image: "{{ .Values.pythonImage.repository }}:{{ .Values.pythonImage.tag }}"
        args: ["backup"]
        imagePullPolicy: {{ .Values.pythonImage.pullPolicy }}
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
      {{- end }}
      containers:
      - name: migrate
        image: "{{ .Values.pythonImage.repository }}:{{ .Values.pythonImage.tag }}"
        args: ["migrate"]
        env:
          - name: "MAINTENANCE_MODE"
            value: "1"
        imagePullPolicy: {{ .Values.pythonImage.pullPolicy }}
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
      restartPolicy: Never
      volumes:
        - name: sites-dir
          persistentVolumeClaim:
            {{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
            {{- else }}
            claimName: {{ template "erpnext.fullname" . }}
            {{- end }}
            readOnly: false
{{- end }}
